<a href="https://colab.research.google.com/github/aishwary-vansh/Fraud-Detection-GNN-/blob/main/notebooks/FinancialFraud.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [ ]:
!unzip "archive(6).zip"

Archive:  archive(6).zip
  inflating: elliptic_bitcoin_dataset/elliptic_txs_classes.csv
  inflating: elliptic_bitcoin_dataset/elliptic_txs_edgelist.csv
  inflating: elliptic_bitcoin_dataset/elliptic_txs_features.csv

In [ ]:


features = pd.read_csv("/content/elliptic_bitcoin_dataset/elliptic_txs_features.csv", header=None)
classes = pd.read_csv("/content/elliptic_bitcoin_dataset/elliptic_txs_classes.csv")
edges = pd.read_csv("/content/elliptic_bitcoin_dataset/elliptic_txs_edgelist.csv")

print(features.shape)
print(classes.shape)
print(edges.shape)

(203769, 167)
(203769, 2)
(234355, 2)

In [ ]:
features.head()

         0    1         2         3    ...       163       164       165       166
0  230425980    1 -0.171469 -0.184668  ... -0.131155 -0.097524 -0.120613 -0.119792
1    5530458    1 -0.171484 -0.184668  ... -0.131155 -0.097524 -0.120613 -0.119792
2  232022460    1 -0.172107 -0.184668  ... -0.131155 -0.183671 -0.120613 -0.119792
3  232438397    1  0.163054  1.963790  ... -0.131155  0.677799 -0.120613 -0.119792
4  230460314    1  1.011523 -0.081127  ...  0.326394  1.293750  0.178136  0.179117

[5 rows x 167 columns]

In [ ]:
classes.head()

        txId    class
0  230425980  unknown
1    5530458  unknown
2  232022460  unknown
3  232438397        2
4  230460314  unknown

In [ ]:
edges.shape()

TypeError: 'tuple' object is not callable